eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-quota
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false

